### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by MikeTrizna** [SmithsonianWorkshops/2022-autumn-smithsonian#1]
- [x] Decide and add dates to page
- [x] Recruit instructors and helpers and add to page
- [x] Customize General Information sections to make sense for Smithsonian audience
- [x] Create Eventbrite registration pages, and embed
- [x] Get schedule formatted and linked to lesson pages
- [x] Customize Setup instructions for Smithsonian non-admin computers

**Comment by MikeTrizna** [comment]
Decided on dates and instructors during SI Carpentries meeting on AM of October 5. Added to site in commit [8daffc6](https://github.com/SmithsonianWorkshops/2022-autumn-smithsonian/commit/8daffc6744ced849daab0af5b335be50febab5e7)
